kind: pipeline
name: default

steps:
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: brock5555/recovery
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    dockerfile: Dockerfile

- name: publish
  image: plugins/docker
  settings:
     tags: [ latest]
environment:
     username:
      from_secret: DOCKER_USERNAME
     password:
      from_secret: DOCKER_PASSWORD
